### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by pulkitkp** [Drac-Zhang/LogicApp_For_Teams_OpenAI_Integration#2]
I am getting below error

{
  "error": {
    "code": "404",
    "message": "Resource not found"
  }
}

**Comment by Kiriti96-Ray** [comment]
+1

**Comment by Drac-Zhang** [comment]
@pulkitkp @Kiriti96-Ray 
Did you deploy the Azure Open AI and Azure Storage Account in advance? Please provide detail information when you deploy.

**Comment by Drac-Zhang** [comment]
@pulkitkp @Kiriti96-Ray 
If you experience this exception on "Read Blob" action, then it is an expected exception since this Logic App will save conversation history in blob storage, so the first time you post a message in channel, it will try to read from existing blobs which is not exist yet and create a new blob.

If 404 is from Http action which calling the Open AI, please make sure the Open AI is existing and endpoint is correct: **https://[Open AI resource Name].openai.azure.com/openai/deployments/[Deployment name]/chat/completions?api-version=2023-03-15-preview**

**Comment by Drac-Zhang** [comment]
Close due to idle
